### ISSUE TITLE
Add Field for Granted Directories

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/ui#10]
### What would you like to be added?

Similar to the https://github.com/robolaunch/ui/issues/9.

[Users should be able to select directories to grant permission](https://github.com/robolaunch/robot-operator/pull/189) for Linux user `robolaunch`.

### Why is this needed?

It's needed to extend user's control over a robot or an application.

**Comment by tunahanertekin** [comment]
Regex for input: `^(/([a-z0-9/])+:)*(/[a-z0-9/]+)$`

**Comment by gokhangunduz** [comment]
The feature has been added successfully. This feature will be available for v0.26.0 and later.

Thank you for your interest.
