### ISSUE TITLE
Specify Custom Ports for IDE/VDI

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/ui#11]
### What would you like to be added?

In robot/application creation section, [user should be able to specify custom ports](https://github.com/robolaunch/robot-operator/pull/194) for custom services.

Here's the format: `<PORT-NAME>-<NODE-PORT>:<CONTAINER-PORT>/<PORT-NAME>-<NODE-PORT>:<CONTAINER-PORT>`
an example: `pt01-31414:4978/pt02-31415:2136/pt03-31416:8444`
as regex: `^([a-z0-9]{4}-[0-9]{5}:[0-9]{2,5}\/)*([a-z0-9]{4}-[0-9]{5}:[0-9]{2,5})$`

Fields:
- **Port Name**: 4 char long string, contains alphanumerical characters.
- **Node Port**:  The port that will be reachable from outside of the cluster. (30000-32767) Orchestrator should check the empty node ports and give them to the UI.
- **Container Port**: Port inside the container.

### Why is this needed?

It's needed to extend user's control over a robot or an application.

**Comment by gokhangunduz** [comment]
The feature has been added successfully. This feature will be available for v0.26.0 and later.

Thank you for your interest.
