### ISSUE TITLE
Make GPU Instance Type Selectable

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/ui#12]
### What would you like to be added?

https://github.com/robolaunch/robot-operator/issues/196

Users should be able to select GPU instance type for their services. List of available instances will be queried over MetricsExporter.

### Why is this needed?

It's needed to give users the ability of select GPU capability of their applications/robots.

**Comment by gokhangunduz** [comment]
The feature has been added successfully. This feature will be available for v0.26.0 and later.

Thank you for your interest.

**Comment by tunahanertekin** [comment]
Eyw 🥇
