### ISSUE TITLE
Update Directory Regex

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/ui#14]
### What would you like to be added?

Regular expressions are updated for the configurations:
- Permitted directories
- Persistent directories

New regex: `^(\/([a-z0-9./_-])+:)*(\/[a-z0-9./_-]+)$`

### Why is this needed?

It's needed to allow characters `.`, `-` and `_`.

**Comment by tunahanertekin** [comment]
New regular expressions for advanced setting:

- Granted/Permitted Directories: `^(\/([A-Za-z0-9./_-])+:)*(\/[A-Za-z0-9./_-]+)$`
- Persistent Directories: `^(\/([A-Za-z0-9./_-])+:)*(\/[A-Za-z0-9./_-]+)$`
- Host Directories: `^(((\/[A-Za-z0-9./_-]+):(\/[A-Za-z0-9./_-]+))+,)*(((\/[A-Za-z0-9./_-]+):(\/[A-Za-z0-9./_-]+))+)$`

**Comment by gokhangunduz** [comment]
The feature has been added successfully. This feature will be available for v0.26.0 and later.

Thank you for your interest.
