### ISSUE TITLE
Add VDI Reload Button

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/ui#2]
### What would you like to be added?

User that takes control should be able to reload VDI. Reload button simply should set the resolution again by checking the desired resolution.

### Why is this needed?

It's needed to give users a backup option for fixing VDI anomalies.

**Comment by gokhangunduz** [comment]
Requested feature added. Now users will be able to reload VDI stream connections. Related commits;

#https://github.com/robolaunch/ui/commit/067d781123cabaa3a6a87ca0522a3a2780966c79
#https://github.com/robolaunch/ui/commit/71372e1f0e58d787419ead046fcd46fcf6a25aad

Thanks for your help and interest.
