### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/ui#3]
### What would you like to be updated?

`README.md` should cover:
- project prerequisites
- project setup
- starting local server
- building project
- deployment to various environments (Kubernetes is a priority)

**Comment by gokhangunduz** [comment]
Hi, I updated `README.md` file.

 Related commits;
- https://github.com/robolaunch/ui/commit/f1d75f7c3bd41363041842143bb5cebba2f0ebc7
- https://github.com/robolaunch/ui/commit/b154ff1250973a7ed004f655502eb777283a069a
- https://github.com/robolaunch/ui/commit/eb5ac2f9b0128d41b21651b10ab9e7a455b8ee27


Thanks for your help and interest.
