### ISSUE TITLE
Extend Robot Phase

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/ui#5]
### What would you like to be added?

Robot phases are defined [here](https://github.com/robolaunch/robot-operator/blob/f0724664d9a1df58e37edb9084936bde1308b6e2/pkg/api/roboscale.io/v1alpha1/phases.go#L5) (including unnecessary phases). They need to be extended in UI and be more descriptive. The schema attached below aims to extend these phases:

![Phase Schema drawio](https://github.com/robolaunch/ui/assets/46759747/0ebac1df-8cd9-4ac1-bbd8-af635385704e)

You can split these phases into 3 main phase:

![Phase Schema drawio(1)](https://github.com/robolaunch/ui/assets/46759747/ee7f20b1-46e0-44ff-886b-b3d8c67ebbed)

### Why is this needed?

It's needed to inform user about operations running in the background, especially for longer processes such as configuring ROS 2 environment.

**Comment by tunahanertekin** [comment]
New diagram is added for splitting phases. @gokhangunduz

**Comment by gokhangunduz** [comment]
Hi, components were prepared in which the user was informed in accordance with the scheme.

Thanks for your help and interest.
